name: Publish (GitHub Packages)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node (GitHub Packages)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          cache: 'pnpm'

      - name: Configure .npmrc for scope
        run: |
          echo "@returnacy:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm check

      - name: Build + Generate Schemas
        run: pnpm prepublishOnly

      - name: Verify schemas committed
        run: |
          git add schemas
          if ! git diff --cached --quiet; then
            echo 'Schemas changed. Commit and tag again.'
            git diff --cached
            exit 1
          fi

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

      - name: Summary
        run: |
          echo "Published $(node -p "require('./package.json').name")@$(node -p "require('./package.json').version") to GitHub Packages" >> $GITHUB_STEP_SUMMARY